package hust.parksys.entity;

import java.util.Date;

public class ParkInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.id
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.car_num
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.tollman
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String tollman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.park_name
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String parkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.time_in
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private Date timeIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.time_out
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private Date timeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.duration
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.tolltype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String tolltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.money_bfdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String moneyBfdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.discount_type
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String discountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.discount_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String discountMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.money_afdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String moneyAfdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.money_cash
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String moneyCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.money_e
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String moneyE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.exchange_hours
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String exchangeHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.exchange_minute
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String exchangeMinute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.exchange_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String exchangeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info.lanetype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    private String lanetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.id
     *
     * @return the value of park_info.id
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.id
     *
     * @param id the value for park_info.id
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.car_num
     *
     * @return the value of park_info.car_num
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.car_num
     *
     * @param carNum the value for park_info.car_num
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.tollman
     *
     * @return the value of park_info.tollman
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getTollman() {
        return tollman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.tollman
     *
     * @param tollman the value for park_info.tollman
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setTollman(String tollman) {
        this.tollman = tollman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.park_name
     *
     * @return the value of park_info.park_name
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.park_name
     *
     * @param parkName the value for park_info.park_name
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setParkName(String parkName) {
        this.parkName = parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.time_in
     *
     * @return the value of park_info.time_in
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public Date getTimeIn() {
        return timeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.time_in
     *
     * @param timeIn the value for park_info.time_in
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setTimeIn(Date timeIn) {
        this.timeIn = timeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.time_out
     *
     * @return the value of park_info.time_out
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public Date getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.time_out
     *
     * @param timeOut the value for park_info.time_out
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setTimeOut(Date timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.duration
     *
     * @return the value of park_info.duration
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.duration
     *
     * @param duration the value for park_info.duration
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.tolltype
     *
     * @return the value of park_info.tolltype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getTolltype() {
        return tolltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.tolltype
     *
     * @param tolltype the value for park_info.tolltype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setTolltype(String tolltype) {
        this.tolltype = tolltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.money_bfdiscount
     *
     * @return the value of park_info.money_bfdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getMoneyBfdiscount() {
        return moneyBfdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.money_bfdiscount
     *
     * @param moneyBfdiscount the value for park_info.money_bfdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setMoneyBfdiscount(String moneyBfdiscount) {
        this.moneyBfdiscount = moneyBfdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.discount_type
     *
     * @return the value of park_info.discount_type
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.discount_type
     *
     * @param discountType the value for park_info.discount_type
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.discount_money
     *
     * @return the value of park_info.discount_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getDiscountMoney() {
        return discountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.discount_money
     *
     * @param discountMoney the value for park_info.discount_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setDiscountMoney(String discountMoney) {
        this.discountMoney = discountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.money_afdiscount
     *
     * @return the value of park_info.money_afdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getMoneyAfdiscount() {
        return moneyAfdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.money_afdiscount
     *
     * @param moneyAfdiscount the value for park_info.money_afdiscount
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setMoneyAfdiscount(String moneyAfdiscount) {
        this.moneyAfdiscount = moneyAfdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.money_cash
     *
     * @return the value of park_info.money_cash
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getMoneyCash() {
        return moneyCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.money_cash
     *
     * @param moneyCash the value for park_info.money_cash
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setMoneyCash(String moneyCash) {
        this.moneyCash = moneyCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.money_e
     *
     * @return the value of park_info.money_e
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getMoneyE() {
        return moneyE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.money_e
     *
     * @param moneyE the value for park_info.money_e
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setMoneyE(String moneyE) {
        this.moneyE = moneyE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.exchange_hours
     *
     * @return the value of park_info.exchange_hours
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getExchangeHours() {
        return exchangeHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.exchange_hours
     *
     * @param exchangeHours the value for park_info.exchange_hours
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setExchangeHours(String exchangeHours) {
        this.exchangeHours = exchangeHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.exchange_minute
     *
     * @return the value of park_info.exchange_minute
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getExchangeMinute() {
        return exchangeMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.exchange_minute
     *
     * @param exchangeMinute the value for park_info.exchange_minute
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setExchangeMinute(String exchangeMinute) {
        this.exchangeMinute = exchangeMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.exchange_money
     *
     * @return the value of park_info.exchange_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getExchangeMoney() {
        return exchangeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.exchange_money
     *
     * @param exchangeMoney the value for park_info.exchange_money
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setExchangeMoney(String exchangeMoney) {
        this.exchangeMoney = exchangeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info.lanetype
     *
     * @return the value of park_info.lanetype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public String getLanetype() {
        return lanetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info.lanetype
     *
     * @param lanetype the value for park_info.lanetype
     *
     * @mbggenerated Mon May 15 21:06:51 CST 2017
     */
    public void setLanetype(String lanetype) {
        this.lanetype = lanetype;
    }
}