package hust.parksys.entity;

import java.util.Date;

public class ParkCurrent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info_current.id
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info_current.car_num
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info_current.time
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info_current.type
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_info_current.park_name
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    private String parkName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info_current.id
     *
     * @return the value of park_info_current.id
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info_current.id
     *
     * @param id the value for park_info_current.id
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info_current.car_num
     *
     * @return the value of park_info_current.car_num
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info_current.car_num
     *
     * @param carNum the value for park_info_current.car_num
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info_current.time
     *
     * @return the value of park_info_current.time
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info_current.time
     *
     * @param time the value for park_info_current.time
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info_current.type
     *
     * @return the value of park_info_current.type
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info_current.type
     *
     * @param type the value for park_info_current.type
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_info_current.park_name
     *
     * @return the value of park_info_current.park_name
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_info_current.park_name
     *
     * @param parkName the value for park_info_current.park_name
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    public void setParkName(String parkName) {
        this.parkName = parkName;
    }
}