package hust.parksys.service;

import java.util.List;

import hust.parksys.dto.DtoPark;
import hust.parksys.entity.ParkCurrent;

public interface ParkCurrentService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    int insert(ParkCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    int insertSelective(ParkCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    ParkCurrent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    int updateByPrimaryKeySelective(ParkCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_info_current
     *
     * @mbggenerated Fri May 26 22:25:25 CST 2017
     */
    int updateByPrimaryKey(ParkCurrent record);

	/**
	 * @return
	 */
	List<DtoPark> selectToDay();

	/**
	 * @param carNums 
	 * @return
	 */
	List<DtoPark> selectToDayKeyCars(List<String> carNums);
}